package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"math"
	"os"
)

func main() {
	output := flag.String("output", "climate_tables_generated.go", "generated Go output")
	flag.Parse()
	var source bytes.Buffer
	source.WriteString("// Code generated by tools/generate_climate_tables; DO NOT EDIT.\n\npackage domain\n\n")
	writeTable(&source, "orbitalSinBits", 401, func(turn int) float64 {
		u := progress(turn)
		return math.Sin(8 * math.Pi * u)
	})
	writeTable(&source, "seasonalCosBits", 12, func(season int) float64 {
		return math.Cos(2 * math.Pi * float64(season) / 12)
	})
	writeTable(&source, "precessionSinBits", 401, func(turn int) float64 {
		u := progress(turn)
		return math.Sin(2*math.Pi*(60_000*u/21_000) + 2.020)
	})
	formatted, err := format.Source(source.Bytes())
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile(*output, formatted, 0o644); err != nil {
		panic(err)
	}
}

func writeTable(buffer *bytes.Buffer, name string, count int, value func(int) float64) {
	fmt.Fprintf(buffer, "var %s = [%d]uint64{\n", name, count)
	for index := range count {
		fmt.Fprintf(buffer, "0x%016x,", math.Float64bits(value(index)))
		if index%4 == 3 {
			buffer.WriteByte('\n')
		}
	}
	buffer.WriteString("}\n\n")
}

func progress(turn int) float64 {
	var year int
	switch {
	case turn < 100:
		year = 80_000 - 300*turn
	case turn < 200:
		year = 50_000 - 150*(turn-100)
	case turn < 300:
		year = 35_000 - 100*(turn-200)
	default:
		year = 25_000 - 50*(turn-300)
	}
	return float64(80_000-year) / 60_000
}
